#!/usr/bin/env bash
set -euo pipefail

ROS_WS=/ssd/ros2_ws
NAME=ros_lidar

docker stop "$NAME" 2>/dev/null || true
docker rm   "$NAME" 2>/dev/null || true

docker run -d \
  --name "$NAME" \
  --restart unless-stopped \
  -w "$ROS_WS" \
  --mount type=bind,src="$ROS_WS",dst="$ROS_WS" \
  --network=host \
  -e ROS_DOMAIN_ID=30 \
  --device=/dev/myimu \
  --device=/dev/lidar \
  robot-sensors

