version: 1
rules:
  - name: pause_on_tag_10
    tag_id: 10
    action: stop
    duration_sec: 2.0
    cooldown_sec: 8.0
    priority: 100

  - name: cancel_nav_on_tag_99
    tag_id: 99
    action: cancel_navigation
    cooldown_sec: 5.0
    priority: 120

  - name: relocalize_on_tag_20
    tag_id: 98
    action: set_initial_pose
    use_landmark_pose: true
    frame_id: map
    max_range_m: 1.5
    covariance_xy: 0.25
    covariance_yaw: 0.0685
    cooldown_sec: 20.0
    priority: 180
