apriltag_nav_behavior_tree:
  ros__parameters:
    use_sim_time: true
    detections_topic: /tag_detections
    cmd_vel_topic: /cmd_vel
    initial_pose_topic: /initialpose
    navigate_to_pose_action: /navigate_to_pose
    rules_file: ""
    lifecycle_manager_service: /lifecycle_manager_navigation/manage_nodes
    docking_default_timeout_sec: 12.0
    docking_default_target_range_m: 0.30
    docking_default_linear_x: -0.08
    docking_default_angular_z: 0.0
    docking_sleep_duration_sec: 15.0
    docking_pause_nav2: true
    docking_lidar_power_control_enabled: true
    lidar_stop_motor_service: /stop_motor
    lidar_start_motor_service: /start_motor
    landmarks_file: ""
    map_yaml: ""
    auto_landmarks_from_map: true
    use_landmark_yaw: true
    tick_rate_hz: 5.0
    detection_timeout_sec: 0.75
    default_cooldown_sec: 8.0
    stop_action_default_duration_sec: 1.0
    log_detection_events: false
