foxglove_bridge:
  ros__parameters:
    port: 8765
    address: 0.0.0.0
    tls: false
    use_compression: true
    send_buffer_limit: 10000000
    capabilities:
      - clientPublish
      - parameters
      - parametersSubscribe
      - services
      - connectionGraph
      - assets
