<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>bluebot_v3</name>
  <version>0.1.0</version>
  <description>Bluebot v3 environment mapping stack for Nav2 map generation.</description>
  <maintainer email="hailey@todo.todo">hailey</maintainer>
  <license>Apache-2.0</license>

  <depend>launch</depend>
  <depend>launch_ros</depend>
  <depend>ament_index_python</depend>
  <depend>rclpy</depend>
  <depend>geometry_msgs</depend>
  <depend>nav_msgs</depend>

  <depend>ros2_serial_diff_drive_bridge</depend>
  <depend>lidar_launch</depend>
  <depend>yb_a471_driver</depend>
  <depend>serial_diff_drive_hw</depend>
  <depend>slam_toolbox</depend>
  <depend>robot_localization</depend>
  <depend>tf2_ros</depend>

  <exec_depend>rviz2</exec_depend>
  <exec_depend>nav2_map_server</exec_depend>

  <test_depend>ament_flake8</test_depend>
  <test_depend>ament_pep257</test_depend>
  <test_depend>python3-pytest</test_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
